### ISSUE TITLE
Paypal Mode

### ISSUE THREAD

**Issue by densonclan** [deanperry/shoppe-paypal#11]
Hi, I was wondering if you could explain what I put in the Paypal Mode section of the settings?

**Comment by benzzdan** [comment]
yeah me too...

**Comment by daltonrenaldo** [comment]
`live` or `sandbox`

**Comment by deanpcmad** [comment]
Hey, yep it should be `live` or `sandbox` - https://github.com/deanpcmad/shoppe-paypal/blob/master/lib/shoppe/paypal.rb#L25
