### ISSUE TITLE
Bad Request from shoppe-paypal gem

### ISSUE THREAD

**Issue by 800a7b32** [deanperry/shoppe-paypal#3]
When I follow the guides step-by-step to add the shoppe-paypal gem (http://tryshoppe.com/docs/payment-gateways/paypal), I get a '400 Bad Request' when trying to checkout with valid Paypal Sandbox details.
- Console log: http://paste.codebasehq.com/pastes/ft781cckrlzt0vwtzm
- ![Exception Message](https://cloud.githubusercontent.com/assets/1313697/7447151/fbff7e5c-f1e7-11e4-8f2e-8ff8225d3f7e.png)

Paypal code added to orders_controller.rb (Note: I changed @order = Shoppe::Order.find(session[:current_order_id]) to use current_order.id so that it finds a valid id)

```
def paypal
    @order = Shoppe::Order.find(current_order.id)
    url = @order.redirect_to_paypal(checkout_payment_url(success: true), checkout_payment_url(success: false))
    redirect_to url
end
```

Any pointers?

**Comment by deanpcmad** [comment]
I guess you're using sandbox API details?

**Comment by 800a7b32** [comment]
I guess so - i haven't done anything outside the scope of the tutorial

**Comment by 800a7b32** [comment]
I, [2015-05-03T22:51:47.764294 #6829]  INFO -- : PayPal-Request-Id: 40d1d8a6-f61e-4cd2-8c09-1e9f10b4d843
I, [2015-05-03T22:51:47.764342 #6829]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/payments/payment
I, [2015-05-03T22:51:48.726177 #6829]  INFO -- : Response[400]: Bad Request, Duration: 0.962s
Completed 500 Internal Server Error in 1130ms (ActiveRecord: 32.9ms)

Shoppe::Errors::PaymentDeclined (There was an error contacting the payment processor):
  app/controllers/orders_controller.rb:105:in `paypal'

**Comment by deanpcmad** [comment]
When creating a PayPal REST app, you'll have both Sandbox & Live details - 
![](https://files.deanpcmad.com/2015/D6qIzj0OsX.jpg)

**Comment by 800a7b32** [comment]
correct - i'm using the Sandbox details

![screenshot-23-40-37](https://cloud.githubusercontent.com/assets/1313697/7447316/ee30c5fa-f1ed-11e4-858c-eab1b06a3c2c.png)

**Comment by deanpcmad** [comment]
Odd, will take a look at that then

**Comment by deanpcmad** [comment]
How did you get past #1 btw?

**Comment by 800a7b32** [comment]
Resolved #1 by manually adding the db fields as a workaround :)

**Comment by manzha** [comment]
I kind of made it work adding manually field currency in shoppe-paypal-1.0.0/lib/shoppe/paypal/order_extensions.rb

#:currency => Shoppe::Paypal.currency }, 
:currency => "MXN" }, #MXN or USD, whatever.

That way I could go through the error to the paypal's sandbox page, but it looks like it isn't sending correctly the transaction details (total and currency).
![paypal](https://cloud.githubusercontent.com/assets/5351407/7489294/c9ef32ea-f39a-11e4-9399-85b93bd75d75.png)

Hope this helps!

**Comment by 800a7b32** [comment]
Thanks @manzha - will take a look at this approach later!

**Comment by 800a7b32** [comment]
I can confirm that hard coding EUR (or a currency) works.

**Comment by 800a7b32** [comment]
This issue was caused by the settings area for 'Paypal Currency' not being referenced correctly.

**Comment by flrnt** [comment]
hi @andretanguy, I'm facing the same error (Shoppe::Errors::PaymentDeclined at /checkout/paypal
There was an error contacting the payment processor) with the last version of the gem. Any tips ?
