### ISSUE TITLE
Translation missing: en.shoppe.settings.labels.paypal_client_id

### ISSUE THREAD

**Issue by diraulo** [deanperry/shoppe-paypal#6]
The locale file in `/config/locales/en.yml` is not loaded correctly, which is why the defined labels and help info are not displayed as intended. 

![shoppe-paypal-no-translation](https://cloud.githubusercontent.com/assets/4028374/9460152/95cba4f6-4b03-11e5-86ae-9cca2fe365d4.png)

I could submit a pull request for this if you're interested in fixing this

**Comment by deanpcmad** [comment]
Hey, sure go ahead
